package customer.affeliateconsumer;

/**
 * Created by roman rasskazov on 30.05.2015.
 */
public enum ParameterName {
    LAST_UPDATED_LINKSHARE_SIGNATURE,
    LAST_UPDATED_LINKSHARE_EVENT,
    LAST_UPDATED_LINKSHARE_PAYMENT_HISTORY,
    LAST_UPDATED_CJ_COMMISSION_DETAILS,
    LINKSHARE_PASSWORD,
    LINKSHARE_USERNAME,
    LINKSHARE_SCOPE,
    LINKSHARE_SECURITY_TOKEN,
    REQUEST_REAUTHENTICATION_MINUTES, REST_CONNECTION_TIMEOUT,
    SMTP_HOST,
    SMTP_PORT,
    SMTP_SENT_FROM_MAIL,
    SMTP_SENT_TO_MAIL,
    SMTP_AUTH_PWD,
    SMTP_FROM;
}
