conn = new Mongo();
db = conn.getDB("affiliate_networks");
db.parameters.remove(null);
db.commissions.dropIndexes();
db.parameters.insert({parameter: 'CJ_UPDATE_COMMISSIONS_START_TIME_IN_HOURS', value: '0'});
db.parameters.insert({parameter: 'CJ_UPDATE_COMMISSIONS_RUN_PERIOD_IN_HOURS', value: '0.01'});
db.parameters.insert({parameter: 'CJ_UPDATE_TRANSACTIONS_START_TIME_IN_HOURS', value: '0'});
db.parameters.insert({parameter: 'CJ_UPDATE_TRANSACTIONS_RUN_PERIOD_IN_HOURS', value: '0.01'});
db.parameters.insert({parameter: 'LINKSHARE_UPDATE_COMMISSIONS_START_TIME_IN_HOURS', value: '0'});
db.parameters.insert({parameter: 'LINKSHARE_UPDATE_COMMISSIONS_RUN_PERIOD_IN_HOURS', value: '0.01'});
db.parameters.insert({parameter: 'LINKSHARE_REQUEST_NEW_TRANSACTIONS_START_TIME_IN_HOURS', value: '0'});
db.parameters.insert({parameter: 'LINKSHARE_REQUEST_NEW_TRANSACTIONS_RUN_PERIOD_IN_HOURS', value: '0.01'});
db.parameters.insert({parameter: 'LINKSHARE_REQUEST_CONFIRMED_TRANSACTIONS_START_TIME_IN_HOURS', value: '0'});
db.parameters.insert({parameter: 'LINKSHARE_REQUEST_CONFIRMED_TRANSACTIONS_RUN_PERIOD_IN_HOURS', value: '0.01'});
db.parameters.insert({parameter: 'LINKSHARE_REQUEST_AVAILABLE_TRANSACTIONS_START_TIME_IN_HOURS', value: '0'});
db.parameters.insert({parameter: 'LINKSHARE_REQUEST_AVAILABLE_TRANSACTIONS_RUN_PERIOD_IN_HOURS', value: '0.01'});
db.parameters.insert({parameter: 'LAST_UPDATED_LINKSHARE_EVENT', value: '2015-01-01 00:00:00'});
db.parameters.insert({parameter: 'LAST_UPDATED_LINKSHARE_SIGNATURE', value: '20150101'});
db.parameters.insert({parameter: 'LAST_UPDATED_LINKSHARE_PAYMENT_HISTORY', value: '20150101'});
db.parameters.insert({parameter: 'LAST_UPDATED_CJ_COMMISSION_DETAILS', value: '2015-05-30'});
db.parameters.insert({parameter: 'LINKSHARE_SECURITY_TOKEN', value: 'c3edcc8d5b2f2bfd3e01badc118041c1a9dcdd10a25371e6b3dba1ca1a3d1bac'});
db.parameters.insert({parameter: 'LINKSHARE_USERNAME', value: 'odeskuser1'});
db.parameters.insert({parameter: 'LINKSHARE_PASSWORD', value: 'Odeskuser123'});
db.parameters.insert({parameter: 'LINKSHARE_SCOPE', value: '3241240'});
db.parameters.insert({parameter: 'REQUEST_REAUTHENTICATION_MINUTES', value: '5'});
db.parameters.insert({parameter: 'REST_CONNECTION_TIMEOUT', value: '10000'});
db.parameters.insert({parameter: 'SMTP_HOST', value: 'smtp.zoho.com'});
db.parameters.insert({parameter: 'SMTP_PORT', value: '587'});
db.parameters.insert({parameter: 'SMTP_SENT_FROM_MAIL', value: 'notification@dealyaft.com'});
db.parameters.insert({parameter: 'SMTP_SENT_TO_MAIL', value: 'merajak@hotmail.com'});
db.parameters.insert({parameter: 'SMTP_AUTH_PWD', value: 'Odeskuser1'});
db.parameters.insert({parameter: 'SMTP_FROM', value: 'Rest Consumer'});

db.commissions.createIndex( { "commissions.affiliateNetwrok": 1, "commissions.retailerID": 1, "commissions.orderID": 1 } , { unique: true });
db.commissions.createIndex( { "cuid": 1}, { unique: true } );
